/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeShopRouteImport } from './routes/theme-shop'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as _404RouteImport } from './routes/__404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as SignUpContinueRouteImport } from './routes/sign-up/continue'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in/sso-callback'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'
import { Route as JournalUserProfileRouteImport } from './routes/journal/user-profile'
import { Route as JournalTodoRouteImport } from './routes/journal/todo'
import { Route as JournalDiaryRouteImport } from './routes/journal/diary'
import { Route as JournalDashboardRouteImport } from './routes/journal/dashboard'
import { Route as JournalBeanJourneyRouteImport } from './routes/journal/bean-journey'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as JournalMemoryZoneIndexRouteImport } from './routes/journal/memory-zone/index'
import { Route as JournalProjectProjectIdRouteImport } from './routes/journal/project/$projectId'
import { Route as JournalMemoryZoneZoneIdRouteImport } from './routes/journal/memory-zone/$zoneId'

const ThemeShopRoute = ThemeShopRouteImport.update({
  id: '/theme-shop',
  path: '/theme-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const _404Route = _404RouteImport.update({
  id: '/__404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const SignUpContinueRoute = SignUpContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignInRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalUserProfileRoute = JournalUserProfileRouteImport.update({
  id: '/user-profile',
  path: '/user-profile',
  getParentRoute: () => JournalRoute,
} as any)
const JournalTodoRoute = JournalTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => JournalRoute,
} as any)
const JournalDiaryRoute = JournalDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => JournalRoute,
} as any)
const JournalDashboardRoute = JournalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => JournalRoute,
} as any)
const JournalBeanJourneyRoute = JournalBeanJourneyRouteImport.update({
  id: '/bean-journey',
  path: '/bean-journey',
  getParentRoute: () => JournalRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const JournalMemoryZoneIndexRoute = JournalMemoryZoneIndexRouteImport.update({
  id: '/memory-zone/',
  path: '/memory-zone/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalProjectProjectIdRoute = JournalProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => JournalRoute,
} as any)
const JournalMemoryZoneZoneIdRoute = JournalMemoryZoneZoneIdRouteImport.update({
  id: '/memory-zone/$zoneId',
  path: '/memory-zone/$zoneId',
  getParentRoute: () => JournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/features': typeof FeaturesRoute
  '/journal': typeof JournalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/theme-shop': typeof ThemeShopRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/bean-journey': typeof JournalBeanJourneyRoute
  '/journal/dashboard': typeof JournalDashboardRoute
  '/journal/diary': typeof JournalDiaryRoute
  '/journal/todo': typeof JournalTodoRoute
  '/journal/user-profile': typeof JournalUserProfileRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/continue': typeof SignUpContinueRoute
  '/journal/': typeof JournalIndexRoute
  '/journal/memory-zone/$zoneId': typeof JournalMemoryZoneZoneIdRoute
  '/journal/project/$projectId': typeof JournalProjectProjectIdRoute
  '/journal/memory-zone': typeof JournalMemoryZoneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/theme-shop': typeof ThemeShopRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/bean-journey': typeof JournalBeanJourneyRoute
  '/journal/dashboard': typeof JournalDashboardRoute
  '/journal/diary': typeof JournalDiaryRoute
  '/journal/todo': typeof JournalTodoRoute
  '/journal/user-profile': typeof JournalUserProfileRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/continue': typeof SignUpContinueRoute
  '/journal': typeof JournalIndexRoute
  '/journal/memory-zone/$zoneId': typeof JournalMemoryZoneZoneIdRoute
  '/journal/project/$projectId': typeof JournalProjectProjectIdRoute
  '/journal/memory-zone': typeof JournalMemoryZoneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__404': typeof _404Route
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/features': typeof FeaturesRoute
  '/journal': typeof JournalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/theme-shop': typeof ThemeShopRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/bean-journey': typeof JournalBeanJourneyRoute
  '/journal/dashboard': typeof JournalDashboardRoute
  '/journal/diary': typeof JournalDiaryRoute
  '/journal/todo': typeof JournalTodoRoute
  '/journal/user-profile': typeof JournalUserProfileRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/continue': typeof SignUpContinueRoute
  '/journal/': typeof JournalIndexRoute
  '/journal/memory-zone/$zoneId': typeof JournalMemoryZoneZoneIdRoute
  '/journal/project/$projectId': typeof JournalProjectProjectIdRoute
  '/journal/memory-zone/': typeof JournalMemoryZoneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/features'
    | '/journal'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/theme-shop'
    | '/blog/$slug'
    | '/journal/bean-journey'
    | '/journal/dashboard'
    | '/journal/diary'
    | '/journal/todo'
    | '/journal/user-profile'
    | '/share/$shareId'
    | '/sign-in/sso-callback'
    | '/sign-up/continue'
    | '/journal/'
    | '/journal/memory-zone/$zoneId'
    | '/journal/project/$projectId'
    | '/journal/memory-zone'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/features'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/theme-shop'
    | '/blog/$slug'
    | '/journal/bean-journey'
    | '/journal/dashboard'
    | '/journal/diary'
    | '/journal/todo'
    | '/journal/user-profile'
    | '/share/$shareId'
    | '/sign-in/sso-callback'
    | '/sign-up/continue'
    | '/journal'
    | '/journal/memory-zone/$zoneId'
    | '/journal/project/$projectId'
    | '/journal/memory-zone'
  id:
    | '__root__'
    | '/'
    | '/__404'
    | '/about'
    | '/blog'
    | '/features'
    | '/journal'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/theme-shop'
    | '/blog/$slug'
    | '/journal/bean-journey'
    | '/journal/dashboard'
    | '/journal/diary'
    | '/journal/todo'
    | '/journal/user-profile'
    | '/share/$shareId'
    | '/sign-in/sso-callback'
    | '/sign-up/continue'
    | '/journal/'
    | '/journal/memory-zone/$zoneId'
    | '/journal/project/$projectId'
    | '/journal/memory-zone/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _404Route: typeof _404Route
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  JournalRoute: typeof JournalRouteWithChildren
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  ThemeShopRoute: typeof ThemeShopRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-shop': {
      id: '/theme-shop'
      path: '/theme-shop'
      fullPath: '/theme-shop'
      preLoaderRoute: typeof ThemeShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__404': {
      id: '/__404'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/sign-up/continue': {
      id: '/sign-up/continue'
      path: '/continue'
      fullPath: '/sign-up/continue'
      preLoaderRoute: typeof SignUpContinueRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/sso-callback': {
      id: '/sign-in/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof SignInRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/user-profile': {
      id: '/journal/user-profile'
      path: '/user-profile'
      fullPath: '/journal/user-profile'
      preLoaderRoute: typeof JournalUserProfileRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/todo': {
      id: '/journal/todo'
      path: '/todo'
      fullPath: '/journal/todo'
      preLoaderRoute: typeof JournalTodoRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/diary': {
      id: '/journal/diary'
      path: '/diary'
      fullPath: '/journal/diary'
      preLoaderRoute: typeof JournalDiaryRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/dashboard': {
      id: '/journal/dashboard'
      path: '/dashboard'
      fullPath: '/journal/dashboard'
      preLoaderRoute: typeof JournalDashboardRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/bean-journey': {
      id: '/journal/bean-journey'
      path: '/bean-journey'
      fullPath: '/journal/bean-journey'
      preLoaderRoute: typeof JournalBeanJourneyRouteImport
      parentRoute: typeof JournalRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/journal/memory-zone/': {
      id: '/journal/memory-zone/'
      path: '/memory-zone'
      fullPath: '/journal/memory-zone'
      preLoaderRoute: typeof JournalMemoryZoneIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/project/$projectId': {
      id: '/journal/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/journal/project/$projectId'
      preLoaderRoute: typeof JournalProjectProjectIdRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/memory-zone/$zoneId': {
      id: '/journal/memory-zone/$zoneId'
      path: '/memory-zone/$zoneId'
      fullPath: '/journal/memory-zone/$zoneId'
      preLoaderRoute: typeof JournalMemoryZoneZoneIdRouteImport
      parentRoute: typeof JournalRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface JournalRouteChildren {
  JournalBeanJourneyRoute: typeof JournalBeanJourneyRoute
  JournalDashboardRoute: typeof JournalDashboardRoute
  JournalDiaryRoute: typeof JournalDiaryRoute
  JournalTodoRoute: typeof JournalTodoRoute
  JournalUserProfileRoute: typeof JournalUserProfileRoute
  JournalIndexRoute: typeof JournalIndexRoute
  JournalMemoryZoneZoneIdRoute: typeof JournalMemoryZoneZoneIdRoute
  JournalProjectProjectIdRoute: typeof JournalProjectProjectIdRoute
  JournalMemoryZoneIndexRoute: typeof JournalMemoryZoneIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalBeanJourneyRoute: JournalBeanJourneyRoute,
  JournalDashboardRoute: JournalDashboardRoute,
  JournalDiaryRoute: JournalDiaryRoute,
  JournalTodoRoute: JournalTodoRoute,
  JournalUserProfileRoute: JournalUserProfileRoute,
  JournalIndexRoute: JournalIndexRoute,
  JournalMemoryZoneZoneIdRoute: JournalMemoryZoneZoneIdRoute,
  JournalProjectProjectIdRoute: JournalProjectProjectIdRoute,
  JournalMemoryZoneIndexRoute: JournalMemoryZoneIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface SignInRouteChildren {
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpContinueRoute: typeof SignUpContinueRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpContinueRoute: SignUpContinueRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _404Route: _404Route,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  JournalRoute: JournalRouteWithChildren,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  ThemeShopRoute: ThemeShopRoute,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
